export default [
  {
    titre: "math",
    description: "math",
    classe: "3AP#3AP#3AP",
    id: "math#3AP#3AP#3AP",
  },
  {
    titre: "arabe",
    description: "arabe",
    classe: "3AP#3AP#3AP",
    id: "arabe#3AP#3AP#3AP",
  },
  {
    titre: "science islamique",
    description: "science islamique",
    classe: "3AP#3AP#3AP",
    id: "science islamique#3AP#3AP#3AP",
  },
  {
    titre: "science civile",
    description: "science civile",
    classe: "3AP#3AP#3AP",
    id: "science civile#3AP#3AP#3AP",
  },
  {
    titre: "technologie",
    description: "technologie",
    classe: "3AP#3AP#3AP",
    id: "technologie#3AP#3AP#3AP",
  },
  {
    titre: "français",
    description: "français",
    classe: "3AP#3AP#3AP",
    id: "français#3AP#3AP#3AP",
  },
  {
    titre: "math",
    description: "math",
    classe: "4AP#4AP#4AP",
    id: "math#4AP#4AP#4AP",
  },
  {
    titre: "arabe",
    description: "arabe",
    classe: "4AP#4AP#4AP",
    id: "arabe#4AP#4AP#4AP",
  },
  {
    titre: "science islamique",
    description: "science islamique",
    classe: "4AP#4AP#4AP",
    id: "science islamique#4AP#4AP#4AP",
  },
  {
    titre: "science civile",
    description: "science civile",
    classe: "4AP#4AP#4AP",
    id: "science civile#4AP#4AP#4AP",
  },
  {
    titre: "technologie",
    description: "technologie",
    classe: "4AP#4AP#4AP",
    id: "technologie#4AP#4AP#4AP",
  },
  {
    titre: "français",
    description: "français",
    classe: "4AP#4AP#4AP",
    id: "français#4AP#4AP#4AP",
  },
  {
    titre: "hisoire",
    description: "hisoire",
    classe: "4AP#4AP#4AP",
    id: "hisoire#4AP#4AP#4AP",
  },
  {
    titre: "géographie",
    description: "géographie",
    classe: "4AP#4AP#4AP",
    id: "géographie#4AP#4AP#4AP",
  },
  {
    titre: "math",
    description: "math",
    classe: "5AP#5AP#5AP",
    id: "math#5AP#5AP#5AP",
  },
  {
    titre: "arabe",
    description: "arabe",
    classe: "5AP#5AP#5AP",
    id: "arabe#5AP#5AP#5AP",
  },
  {
    titre: "science islamique",
    description: "science islamique",
    classe: "5AP#5AP#5AP",
    id: "science islamique#5AP#5AP#5AP",
  },
  {
    titre: "science civile",
    description: "science civile",
    classe: "5AP#5AP#5AP",
    id: "science civile#5AP#5AP#5AP",
  },
  {
    titre: "technologie",
    description: "technologie",
    classe: "5AP#5AP#5AP",
    id: "technologie#5AP#5AP#5AP",
  },
  {
    titre: "français",
    description: "français",
    classe: "5AP#5AP#5AP",
    id: "français#5AP#5AP#5AP",
  },
  {
    titre: "hisoire",
    description: "hisoire",
    classe: "5AP#5AP#5AP",
    id: "hisoire#5AP#5AP#5AP",
  },
  {
    titre: "géographie",
    description: "géographie",
    classe: "5AP#5AP#5AP",
    id: "géographie#5AP#5AP#5AP",
  },
  {
    titre: "science naturelle",
    description: "Science naturelle",
    classe: "1AM#1AM#1AM",
    id: "science naturelle#1AM#1AM#1AM",
  },
  {
    titre: "physique",
    description: "physique",
    classe: "1AM#1AM#1AM",
    id: "physique#1AM#1AM#1AM",
  },
  {
    titre: "math",
    description: "math",
    classe: "1AM#1AM#1AM",
    id: "math#1AM#1AM#1AM",
  },
  {
    titre: "arabe",
    description: "arabe",
    classe: "1AM#1AM#1AM",
    id: "arabe#1AM#1AM#1AM",
  },
  {
    titre: "science islamique",
    description: "science islamique",
    classe: "1AM#1AM#1AM",
    id: "science islamique#1AM#1AM#1AM",
  },
  {
    titre: "science civile",
    description: "science civile",
    classe: "1AM#1AM#1AM",
    id: "science civile#1AM#1AM#1AM",
  },
  {
    titre: "français",
    description: "français",
    classe: "1AM#1AM#1AM",
    id: "français#1AM#1AM#1AM",
  },
  {
    titre: "anglais",
    description: "anglais",
    classe: "1AM#1AM#1AM",
    id: "anglais#1AM#1AM#1AM",
  },
  {
    titre: "hisoire",
    description: "hisoire",
    classe: "1AM#1AM#1AM",
    id: "hisoire#1AM#1AM#1AM",
  },
  {
    titre: "géographie",
    description: "géographie",
    classe: "1AM#1AM#1AM",
    id: "géographie#1AM#1AM#1AM",
  },
  {
    titre: "science naturelle",
    description: "Science naturelle",
    classe: "2AM#2AM#2AM",
    id: "science naturelle#2AM#2AM#2AM",
  },
  {
    titre: "physique",
    description: "physique",
    classe: "2AM#2AM#2AM",
    id: "physique#2AM#2AM#2AM",
  },
  {
    titre: "math",
    description: "math",
    classe: "2AM#2AM#2AM",
    id: "math#2AM#2AM#2AM",
  },
  {
    titre: "arabe",
    description: "arabe",
    classe: "2AM#2AM#2AM",
    id: "arabe#2AM#2AM#2AM",
  },
  {
    titre: "science islamique",
    description: "science islamique",
    classe: "2AM#2AM#2AM",
    id: "science islamique#2AM#2AM#2AM",
  },
  {
    titre: "science civile",
    description: "science civile",
    classe: "2AM#2AM#2AM",
    id: "science civile#2AM#2AM#2AM",
  },
  {
    titre: "français",
    description: "français",
    classe: "2AM#2AM#2AM",
    id: "français#2AM#2AM#2AM",
  },
  {
    titre: "anglais",
    description: "anglais",
    classe: "2AM#2AM#2AM",
    id: "anglais#2AM#2AM#2AM",
  },
  {
    titre: "hisoire",
    description: "hisoire",
    classe: "2AM#2AM#2AM",
    id: "hisoire#2AM#2AM#2AM",
  },
  {
    titre: "géographie",
    description: "géographie",
    classe: "2AM#2AM#2AM",
    id: "géographie#2AM#2AM#2AM",
  },
  {
    titre: "science naturelle",
    description: "Science naturelle",
    classe: "3AM#3AM#3AM",
    id: "science naturelle#3AM#3AM#3AM",
  },
  {
    titre: "physique",
    description: "physique",
    classe: "3AM#3AM#3AM",
    id: "physique#3AM#3AM#3AM",
  },
  {
    titre: "math",
    description: "math",
    classe: "3AM#3AM#3AM",
    id: "math#3AM#3AM#3AM",
  },
  {
    titre: "arabe",
    description: "arabe",
    classe: "3AM#3AM#3AM",
    id: "arabe#3AM#3AM#3AM",
  },
  {
    titre: "science islamique",
    description: "science islamique",
    classe: "3AM#3AM#3AM",
    id: "science islamique#3AM#3AM#3AM",
  },
  {
    titre: "science civile",
    description: "science civile",
    classe: "3AM#3AM#3AM",
    id: "science civile#3AM#3AM#3AM",
  },
  {
    titre: "français",
    description: "français",
    classe: "3AM#3AM#3AM",
    id: "français#3AM#3AM#3AM",
  },
  {
    titre: "anglais",
    description: "anglais",
    classe: "3AM#3AM#3AM",
    id: "anglais#3AM#3AM#3AM",
  },
  {
    titre: "hisoire",
    description: "hisoire",
    classe: "3AM#3AM#3AM",
    id: "hisoire#3AM#3AM#3AM",
  },
  {
    titre: "géographie",
    description: "géographie",
    classe: "3AM#3AM#3AM",
    id: "géographie#3AM#3AM#3AM",
  },
  {
    titre: "science naturelle",
    description: "Science naturelle",
    classe: "4AM#4AM#4AM",
    id: "science naturelle#4AM#4AM#4AM",
  },
  {
    titre: "physique",
    description: "physique",
    classe: "4AM#4AM#4AM",
    id: "physique#4AM#4AM#4AM",
  },
  {
    titre: "math",
    description: "math",
    classe: "4AM#4AM#4AM",
    id: "math#4AM#4AM#4AM",
  },
  {
    titre: "arabe",
    description: "arabe",
    classe: "4AM#4AM#4AM",
    id: "arabe#4AM#4AM#4AM",
  },
  {
    titre: "science islamique",
    description: "science islamique",
    classe: "4AM#4AM#4AM",
    id: "science islamique#4AM#4AM#4AM",
  },
  {
    titre: "science civile",
    description: "science civile",
    classe: "4AM#4AM#4AM",
    id: "science civile#4AM#4AM#4AM",
  },
  {
    titre: "français",
    description: "français",
    classe: "4AM#4AM#4AM",
    id: "français#4AM#4AM#4AM",
  },
  {
    titre: "anglais",
    description: "anglais",
    classe: "4AM#4AM#4AM",
    id: "anglais#4AM#4AM#4AM",
  },
  {
    titre: "hisoire",
    description: "hisoire",
    classe: "4AM#4AM#4AM",
    id: "hisoire#4AM#4AM#4AM",
  },
  {
    titre: "géographie",
    description: "géographie",
    classe: "4AM#4AM#4AM",
    id: "géographie#4AM#4AM#4AM",
  },
  {
    titre: "science naturelle",
    description: "Science naturelle",
    classe: "1AS#1AS#1AS",
    id: "science naturelle#1AS#1AS#1AS",
  },
  {
    titre: "physique",
    description: "physique",
    classe: "1AS#1AS#1AS",
    id: "physique#1AS#1AS#1AS",
  },
  {
    titre: "math",
    description: "math",
    classe: "1AS#1AS#1AS",
    id: "math#1AS#1AS#1AS",
  },
  {
    titre: "arabe",
    description: "arabe",
    classe: "1AS#1AS#1AS",
    id: "arabe#1AS#1AS#1AS",
  },
  {
    titre: "science islamique",
    description: "شريعة إسلامية",
    classe: "1AS#1AS#1AS",
    id: "science islamique#1AS#1AS#1AS",
  },
  {
    titre: "français",
    description: "français",
    classe: "1AS#1AS#1AS",
    id: "français#1AS#1AS#1AS",
  },
  {
    titre: "anglais",
    description: "anglais",
    classe: "1AS#1AS#1AS",
    id: "anglais#1AS#1AS#1AS",
  },
  {
    titre: "hisoire",
    description: "hisoire",
    classe: "1AS#1AS#1AS",
    id: "hisoire#1AS#1AS#1AS",
  },
  {
    titre: "géographie",
    description: "géographie",
    classe: "1AS#1AS#1AS",
    id: "géographie#1AS#1AS#1AS",
  },
  {
    titre: "science naturelle",
    description: "Science naturelle",
    classe: "1AL#1AL#1AL",
    id: "science naturelle#1AL#1AL#1AL",
  },
  {
    titre: "physique",
    description: "physique",
    classe: "1AL#1AL#1AL",
    id: "physique#1AL#1AL#1AL",
  },
  {
    titre: "math",
    description: "math",
    classe: "1AL#1AL#1AL",
    id: "math#1AL#1AL#1AL",
  },
  {
    titre: "arabe",
    description: "arabe",
    classe: "1AL#1AL#1AL",
    id: "arabe#1AL#1AL#1AL",
  },
  {
    titre: "science islamique",
    description: "شريعة إسلامية",
    classe: "1AL#1AL#1AL",
    id: "science islamique#1AL#1AL#1AL",
  },
  {
    titre: "français",
    description: "français",
    classe: "1AL#1AL#1AL",
    id: "français#1AL#1AL#1AL",
  },
  {
    titre: "anglais",
    description: "anglais",
    classe: "1AL#1AL#1AL",
    id: "anglais#1AL#1AL#1AL",
  },
  {
    titre: "hisoire",
    description: "hisoire",
    classe: "1AL#1AL#1AL",
    id: "hisoire#1AL#1AL#1AL",
  },
  {
    titre: "géographie",
    description: "géographie",
    classe: "1AL#1AL#1AL",
    id: "géographie#1AL#1AL#1AL",
  },
  {
    titre: "science naturelle",
    description: "Science naturelle",
    classe: "2S#2S#2S",
    id: "science naturelle#2S#2S#2S",
  },
  {
    titre: "physique",
    description: "physique",
    classe: "2S#2S#2S",
    id: "physique#2S#2S#2S",
  },
  {
    titre: "math",
    description: "math",
    classe: "2S#2S#2S",
    id: "math#2S#2S#2S",
  },
  {
    titre: "arabe",
    description: "arabe",
    classe: "2S#2S#2S",
    id: "arabe#2S#2S#2S",
  },
  {
    titre: "science islamique",
    description: "شريعة إسلامية",
    classe: "2S#2S#2S",
    id: "science islamique#2S#2S#2S",
  },
  {
    titre: "français",
    description: "français",
    classe: "2S#2S#2S",
    id: "français#2S#2S#2S",
  },
  {
    titre: "anglais",
    description: "anglais",
    classe: "2S#2S#2S",
    id: "anglais#2S#2S#2S",
  },
  {
    titre: "hisoire",
    description: "hisoire",
    classe: "2S#2S#2S",
    id: "hisoire#2S#2S#2S",
  },
  {
    titre: "géographie",
    description: "géographie",
    classe: "2S#2S#2S",
    id: "géographie#2S#2S#2S",
  },
  {
    titre: "science naturelle",
    description: "Science naturelle",
    classe: "2M#2M#2M",
    id: "science naturelle#2M#2M#2M",
  },
  {
    titre: "physique",
    description: "physique",
    classe: "2M#2M#2M",
    id: "physique#2M#2M#2M",
  },
  {
    titre: "math",
    description: "math",
    classe: "2M#2M#2M",
    id: "math#2M#2M#2M",
  },
  {
    titre: "arabe",
    description: "arabe",
    classe: "2M#2M#2M",
    id: "arabe#2M#2M#2M",
  },
  {
    titre: "science islamique",
    description: "شريعة إسلامية",
    classe: "2M#2M#2M",
    id: "science islamique#2M#2M#2M",
  },
  {
    titre: "français",
    description: "français",
    classe: "2M#2M#2M",
    id: "français#2M#2M#2M",
  },
  {
    titre: "anglais",
    description: "anglais",
    classe: "2M#2M#2M",
    id: "anglais#2M#2M#2M",
  },
  {
    titre: "hisoire",
    description: "hisoire",
    classe: "2M#2M#2M",
    id: "hisoire#2M#2M#2M",
  },
  {
    titre: "géographie",
    description: "géographie",
    classe: "2M#2M#2M",
    id: "géographie#2M#2M#2M",
  },
  {
    titre: "science naturelle",
    description: "Science naturelle",
    classe: "2TM#2TM#2TM",
    id: "science naturelle#2TM#2TM#2TM",
  },
  {
    titre: "physique",
    description: "physique",
    classe: "2TM#2TM#2TM",
    id: "physique#2TM#2TM#2TM",
  },
  {
    titre: "math",
    description: "math",
    classe: "2TM#2TM#2TM",
    id: "math#2TM#2TM#2TM",
  },
  {
    titre: "arabe",
    description: "arabe",
    classe: "2TM#2TM#2TM",
    id: "arabe#2TM#2TM#2TM",
  },
  {
    titre: "science islamique",
    description: "شريعة إسلامية",
    classe: "2TM#2TM#2TM",
    id: "science islamique#2TM#2TM#2TM",
  },
  {
    titre: "français",
    description: "français",
    classe: "2TM#2TM#2TM",
    id: "français#2TM#2TM#2TM",
  },
  {
    titre: "anglais",
    description: "anglais",
    classe: "2TM#2TM#2TM",
    id: "anglais#2TM#2TM#2TM",
  },
  {
    titre: "hisoire",
    description: "hisoire",
    classe: "2TM#2TM#2TM",
    id: "hisoire#2TM#2TM#2TM",
  },
  {
    titre: "géographie",
    description: "géographie",
    classe: "2TM#2TM#2TM",
    id: "géographie#2TM#2TM#2TM",
  },
  {
    titre: "gm",
    description: "gm",
    classe: "2TM#2TM#2TM",
    id: "gm#2TM#2TM#2TM",
  },
  {
    titre: "science naturelle",
    description: "Science naturelle",
    classe: "2G#2G#2G",
    id: "science naturelle#2G#2G#2G",
  },
  {
    titre: "physique",
    description: "physique",
    classe: "2G#2G#2G",
    id: "physique#2G#2G#2G",
  },
  {
    titre: "math",
    description: "math",
    classe: "2G#2G#2G",
    id: "math#2G#2G#2G",
  },
  {
    titre: "arabe",
    description: "arabe",
    classe: "2G#2G#2G",
    id: "arabe#2G#2G#2G",
  },
  {
    titre: "science islamique",
    description: "شريعة إسلامية",
    classe: "2G#2G#2G",
    id: "science islamique#2G#2G#2G",
  },
  {
    titre: "français",
    description: "français",
    classe: "2G#2G#2G",
    id: "français#2G#2G#2G",
  },
  {
    titre: "anglais",
    description: "anglais",
    classe: "2G#2G#2G",
    id: "anglais#2G#2G#2G",
  },
  {
    titre: "hisoire",
    description: "hisoire",
    classe: "2G#2G#2G",
    id: "hisoire#2G#2G#2G",
  },
  {
    titre: "géographie",
    description: "géographie",
    classe: "2G#2G#2G",
    id: "géographie#2G#2G#2G",
  },
  {
    titre: "comptabilité",
    description: "comptabilité",
    classe: "2G#2G#2G",
    id: "comptabilité#2G#2G#2G",
  },
  {
    titre: "science naturelle",
    description: "Science naturelle",
    classe: "3S#3S#3S",
    id: "science naturelle#3S#3S#3S",
  },
  {
    titre: "science naturelle",
    description: "Science naturelle",
    classe: "3M#3M#3M",
    id: "science naturelle#3M#3M#3M",
  },
  {
    titre: "science naturelle",
    description: "Science naturelle",
    classe: "3TM#3TM#3TM",
    id: "science naturelle#3TM#3TM#3TM",
  },
  {
    titre: "physique",
    description: "physique",
    classe: "3TM#3TM#3TM",
    id: "physique#3TM#3TM#3TM",
  },
  {
    titre: "math",
    description: "math",
    classe: "3TM#3TM#3TM",
    id: "math#3TM#3TM#3TM",
  },
  {
    titre: "arabe",
    description: "arabe",
    classe: "3TM#3TM#3TM",
    id: "arabe#3TM#3TM#3TM",
  },
  {
    titre: "science islamique",
    description: "شريعة إسلامية",
    classe: "3TM#3TM#3TM",
    id: "science islamique#3TM#3TM#3TM",
  },
  {
    titre: "français",
    description: "français",
    classe: "3TM#3TM#3TM",
    id: "français#3TM#3TM#3TM",
  },
  {
    titre: "anglais",
    description: "anglais",
    classe: "3TM#3TM#3TM",
    id: "anglais#3TM#3TM#3TM",
  },
  {
    titre: "hisoire",
    description: "hisoire",
    classe: "3TM#3TM#3TM",
    id: "hisoire#3TM#3TM#3TM",
  },
  {
    titre: "géographie",
    description: "géographie",
    classe: "3TM#3TM#3TM",
    id: "géographie#3TM#3TM#3TM",
  },
  {
    titre: "gm",
    description: "gm",
    classe: "3TM#3TM#3TM",
    id: "gm#3TM#3TM#3TM",
  },
  {
    titre: "science naturelle",
    description: "Science naturelle",
    classe: "3G#3G#3G",
    id: "science naturelle#3G#3G#3G",
  },
  {
    titre: "physique",
    description: "physique",
    classe: "3G#3G#3G",
    id: "physique#3G#3G#3G",
  },
  {
    titre: "math",
    description: "math",
    classe: "3G#3G#3G",
    id: "math#3G#3G#3G",
  },
  {
    titre: "arabe",
    description: "arabe",
    classe: "3G#3G#3G",
    id: "arabe#3G#3G#3G",
  },
  {
    titre: "science islamique",
    description: "شريعة إسلامية",
    classe: "3G#3G#3G",
    id: "science islamique#3G#3G#3G",
  },
  {
    titre: "français",
    description: "français",
    classe: "3G#3G#3G",
    id: "français#3G#3G#3G",
  },
  {
    titre: "anglais",
    description: "anglais",
    classe: "3G#3G#3G",
    id: "anglais#3G#3G#3G",
  },
  {
    titre: "hisoire",
    description: "hisoire",
    classe: "3G#3G#3G",
    id: "hisoire#3G#3G#3G",
  },
  {
    titre: "géographie",
    description: "géographie",
    classe: "3G#3G#3G",
    id: "géographie#3G#3G#3G",
  },
  {
    titre: "comptabilité",
    description: "comptabilité",
    classe: "3G#3G#3G",
    id: "comptabilité#3G#3G#3G",
  },
];
