export default [
  
  {
    codeCl: "3AP",
    cycle: 1,
    annee: 3,
    description: "3eme anne primaire",
    matieres: ["math#$$$#$$#","arabe#$$$#$$#","science islamique#$$$#$$#","science civile#$$$#$$#","technologie#$$$#$$#","français#$$$#$$#"],
    id: "3AP#3AP#3AP",
  },
  {
    codeCl: "4AP",
    cycle: 1,
    annee: 4,
    description: "4eme anne primaire",
    matieres: ["math#$$$#$$#","arabe#$$$#$$#","science islamique#$$$#$$#","science civile#$$$#$$#","technologie#$$$#$$#","français#$$$#$$#","hisoire#$$$$$$$$$$","géographie#$$$$$$$$$$"],
    id: "4AP#4AP#4AP",
  },
  {
    codeCl: "5AP",
    cycle: 1,
    annee: 5,
    description: "5eme anne primaire",
    matieres: ["math#$$$#$$#","arabe#$$$#$$#","science islamique#$$$#$$#","science civile#$$$#$$#","technologie#$$$#$$#","français#$$$#$$#","hisoire#$$$$$$$$$$","géographie#$$$$$$$$$$"],
    id: "5AP#5AP#5AP",
  },
  {
    codeCl: "1AM",
    cycle: 2,
    annee: 1,
    description: "1er anne moyenne",
    matieres: ["math#$$$#$$#","arabe#$$$#$$#","science islamique#$$$#$$#","science civile#$$$#$$#","français#$$$#$$#","hisoire#$$$$$$$$$$","géographie#$$$$$$$$$$","science naturelle#$*$*$*$*$*$*$*$*$*$","physique#$*$*$*$*$*$*$*$*$*$","anglais#$*$*$*$*$*$*$*$*$*$"],
    id: "1AM#1AM#1AM",
  },
  {
    codeCl: "2AM",
    cycle: 2,
    annee: 2,
    description: "2eme anne moyenne",
    matieres: ["math#$$$#$$#","arabe#$$$#$$#","science islamique#$$$#$$#","science civile#$$$#$$#","français#$$$#$$#","hisoire#$$$$$$$$$$","géographie#$$$$$$$$$$","science naturelle#$*$*$*$*$*$*$*$*$*$","physique#$*$*$*$*$*$*$*$*$*$","anglais#$*$*$*$*$*$*$*$*$*$"],
    id: "2AM#2AM#2AM",
  },
  {
    codeCl: "3AM",
    cycle: 2,
    annee: 3,
    description: "3eme anne moyenne",
    matieres: ["math#$$$#$$#","arabe#$$$#$$#","science islamique#$$$#$$#","science civile#$$$#$$#","français#$$$#$$#","hisoire#$$$$$$$$$$","géographie#$$$$$$$$$$","science naturelle#$*$*$*$*$*$*$*$*$*$","physique#$*$*$*$*$*$*$*$*$*$","anglais#$*$*$*$*$*$*$*$*$*$"],
    id: "3AM#3AM#3AM",
  },
  {
    codeCl: "4AM",
    cycle: 2,
    annee: 4,
    description: "4eme anne moyenne",
    matieres: ["math#$$$#$$#","arabe#$$$#$$#","science islamique#$$$#$$#","science civile#$$$#$$#","français#$$$#$$#","hisoire#$$$$$$$$$$","géographie#$$$$$$$$$$","science naturelle#$*$*$*$*$*$*$*$*$*$","physique#$*$*$*$*$*$*$*$*$*$","anglais#$*$*$*$*$*$*$*$*$*$"],
    id: "4AM#4AM#4AM",
  },
  {
    codeCl: "1AS",
    cycle: 3,
    annee: 1,
    description: "1er anne scientifique",
    matieres: ["math#$$$#$$#","arabe#$$$#$$#","science islamique#SHARI3A","français#$$$#$$#","hisoire#$$$$$$$$$$","géographie#$$$$$$$$$$","science naturelle#$*$*$*$*$*$*$*$*$*$","physique#$*$*$*$*$*$*$*$*$*$","anglais#$*$*$*$*$*$*$*$*$*$"],
    id: "1AS#1AS#1AS",
  },
  {
    codeCl: "1AL",
    cycle: 3,
    annee: 1,
    description: "2eme anne literaire",
    matieres: ["math#$$$#$$#","arabe#$$$#$$#","science islamique#SHARI3A","français#$$$#$$#","hisoire#$$$$$$$$$$","géographie#$$$$$$$$$$","science naturelle#$*$*$*$*$*$*$*$*$*$","physique#$*$*$*$*$*$*$*$*$*$","anglais#$*$*$*$*$*$*$*$*$*$"],
    id: "1AL#1AL#1AL",
  },
  {
    codeCl: "2S",
    cycle: 3,
    annee: 2,
    description: "2eme anne science",
    matieres: ["math#$$$#$$#","arabe#$$$#$$#","science islamique#SHARI3A","français#$$$#$$#","hisoire#$$$$$$$$$$","géographie#$$$$$$$$$$","science naturelle#$*$*$*$*$*$*$*$*$*$","physique#$*$*$*$*$*$*$*$*$*$","anglais#$*$*$*$*$*$*$*$*$*$"],
    id: "2S#2S#2S",
  },
  {
    codeCl: "2M",
    cycle: 3,
    annee: 2,
    description: "2eme anne math",
    matieres: ["math#$$$#$$#","arabe#$$$#$$#","science islamique#SHARI3A","français#$$$#$$#","hisoire#$$$$$$$$$$","géographie#$$$$$$$$$$","science naturelle#$*$*$*$*$*$*$*$*$*$","physique#$*$*$*$*$*$*$*$*$*$","anglais#$*$*$*$*$*$*$*$*$*$"],
    id: "2M#2M#2M",
  },
  {
    codeCl: "2TM",
    cycle: 3,
    annee: 2,
    description: "2eme anne technique mathematique",
    matieres: ["math#$$$#$$#","arabe#$$$#$$#","science islamique#SHARI3A","français#$$$#$$#","hisoire#$$$$$$$$$$","géographie#$$$$$$$$$$","gm#2TM#2TM#2TM","elect#2TM#2TM#2TM","physique#$*$*$*$*$*$*$*$*$*$","anglais#$*$*$*$*$*$*$*$*$*$"],
    id: "2TM#2TM#2TM",
  },
  {
    codeCl: "2G",
    cycle: 3,
    annee: 2,
    description: "2eme anne gestion",
    matieres: ["math#$$$#$$#","arabe#$$$#$$#","science islamique#SHARI3A","français#$$$#$$#","hisoire#$$$$$$$$$$","géographie#$$$$$$$$$$","comptabilité#2G#2G#2G","physique#$*$*$*$*$*$*$*$*$*$","anglais#$*$*$*$*$*$*$*$*$*$"],
    id: "2G#2G#2G",
  },
  {
    codeCl: "3S",
    cycle: 3,
    annee: 3,
    description: "3eme anne science",
    matieres: ["math#$$$#$$#","arabe#$$$#$$#","science islamique#SHARI3A","français#$$$#$$#","hisoire#$$$$$$$$$$","géographie#$$$$$$$$$$","science naturelle#$*$*$*$*$*$*$*$*$*$","physique#$*$*$*$*$*$*$*$*$*$","anglais#$*$*$*$*$*$*$*$*$*$"],
    id: "3S#3S#3S",
  },
  {
    codeCl: "3M",
    cycle: 3,
    annee: 3,
    description: "3eme anne math",
    matieres: ["math#$$$#$$#","arabe#$$$#$$#","science islamique#SHARI3A","français#$$$#$$#","hisoire#$$$$$$$$$$","géographie#$$$$$$$$$$","science naturelle#$*$*$*$*$*$*$*$*$*$","physique#$*$*$*$*$*$*$*$*$*$","anglais#$*$*$*$*$*$*$*$*$*$"],
    id: "3M#3M#3M",
  },
  {
    codeCl: "3TM",
    cycle: 3,
    annee: 3,
    description: "3eme anne technique mathematique",
    matieres: ["math#$$$#$$#","arabe#$$$#$$#","science islamique#SHARI3A","français#$$$#$$#","hisoire#$$$$$$$$$$","géographie#$$$$$$$$$$","gm#2TM#2TM#2TM","elect#2TM#2TM#2TM","physique#$*$*$*$*$*$*$*$*$*$","anglais#$*$*$*$*$*$*$*$*$*$"],
    id: "3TM#3TM#3TM",
  },
  {
    codeCl: "3G",
    cycle: 3,
    annee: 3,
    description: "3eme anne gestion",
    matieres: ["math#$$$#$$#","arabe#$$$#$$#","science islamique#SHARI3A","français#$$$#$$#","hisoire#$$$$$$$$$$","géographie#$$$$$$$$$$","comptabilité#2G#2G#2G","physique#$*$*$*$*$*$*$*$*$*$","anglais#$*$*$*$*$*$*$*$*$*$"],
    id: "3G#3G#3G",
  },
];
