module.exports = [
  {
    codeCl: "3AP",
    cycle: 1,
    annee: 3,
    description: "3ème année primaire",
    matieres: ["math", "arabe", "français"],
  },
  {
    codeCl: "4AP",
    cycle: 1,
    annee: 4,
    description: "4ème année primaire",
    matieres: ["math", "arabe", "français"],
  },
  {
    codeCl: "5AP",
    cycle: 1,
    annee: 5,
    description: "5ème année primaire",
    matieres: ["math", "arabe", "français"],
  },
  {
    codeCl: "1AM",
    cycle: 2,
    annee: 1,
    description: "1ère année moyenne",
    matieres: [
      "math",
      "arabe",
      "français",
      "hisoire",
      "géographie",
      "sciences naturelles",
      "physique",
      "anglais",
    ],
  },
  {
    codeCl: "2AM",
    cycle: 2,
    annee: 2,
    description: "2ème année moyenne",
    matieres: [
      "math",
      "arabe",
      "français",
      "hisoire",
      "géographie",
      "sciences naturelles",
      "physique",
      "anglais",
    ],
  },
  {
    codeCl: "3AM",
    cycle: 2,
    annee: 3,
    description: "3ème année moyenne",
    matieres: [
      "math",
      "arabe",
      "français",
      "hisoire",
      "géographie",
      "sciences naturelles",
      "physique",
      "anglais",
    ],
  },
  {
    codeCl: "4AM",
    cycle: 2,
    annee: 4,
    description: "4ème année moyenne",
    matieres: [
      "math",
      "arabe",
      "français",
      "hisoire",
      "géographie",
      "sciences naturelles",
      "physique",
      "anglais",
    ],
  },
  {
    codeCl: "1AS",
    cycle: 3,
    annee: 1,
    description: "1ere année scientifique",
    matieres: [
      "math",
      "arabe",
      "français",
      "hisoire",
      "géographie",
      "sciences naturelles",
      "physique",
      "anglais",
    ],
  },
  {
    codeCl: "1AL",
    cycle: 3,
    annee: 1,
    description: "1ere année literaire",
    matieres: [
      "math",
      "arabe",
      "français",
      "hisoire",
      "géographie",
      "sciences naturelles",
      "physique",
      "anglais",
    ],
  },
  {
    codeCl: "2AS",
    cycle: 3,
    annee: 2,
    description: "2ème année science",
    matieres: [
      "math",
      "arabe",
      "français",
      "hisoire",
      "géographie",
      "sciences naturelles",
      "physique",
      "anglais",
    ],
  },
  {
    codeCl: "2M",
    cycle: 3,
    annee: 2,
    description: "2ème année math",
    matieres: [
      "math",
      "arabe",
      "français",
      "hisoire",
      "géographie",
      "sciences naturelles",
      "physique",
      "anglais",
    ],
  },
  {
    codeCl: "2TM",
    cycle: 3,
    annee: 2,
    description: "2ème année technique mathematique",
    matieres: [
      "math",
      "arabe",
      "français",
      "hisoire",
      "géographie",
      "Génie mecanique",
      "Génie électrique",
      "physique",
      "anglais",
    ],
  },
  {
    codeCl: "2G",
    cycle: 3,
    annee: 2,
    description: "2ème année gestion",
    matieres: [
      "math",
      "arabe",
      "français",
      "hisoire",
      "géographie",
      "Comptabilité",
      "physique",
      "anglais",
    ],
  },
  {
    codeCl: "3AS",
    cycle: 3,
    annee: 3,
    description: "3ème année science",
    matieres: [
      "math",
      "arabe",
      "français",
      "hisoire",
      "géographie",
      "sciences naturelles",
      "physique",
      "anglais",
    ],
  },
  {
    codeCl: "3M",
    cycle: 3,
    annee: 3,
    description: "3ème année math",
    matieres: [
      "math",
      "arabe",
      "français",
      "hisoire",
      "géographie",
      "sciences naturelles",
      "physique",
      "anglais",
    ],
  },
  {
    codeCl: "3TM",
    cycle: 3,
    annee: 3,
    description: "3ème année technique mathematique",
    matieres: [
      "math",
      "arabe",
      "français",
      "hisoire",
      "géographie",
      "Génie mecanique",
      "Génie électrique",
      "physique",
      "anglais",
    ],
  },
  {
    codeCl: "3G",
    cycle: 3,
    annee: 3,
    description: "3ème année gestion",
    matieres: [
      "math",
      "arabe",
      "français",
      "hisoire",
      "géographie",
      "Comptabilité",
      "physique",
      "anglais",
    ],
  },
];
